packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - lefthook
catalog:
  "@biomejs/biome": ^1.9.4
  "@catppuccin/vscode": ^3.16.1
  "@fontsource/ibm-plex-mono": ^5.1.1
  "@fontsource/ibm-plex-sans-jp": ^5.1.1
  "@monaco-editor/react": ^4.7.0
  "@shikijs/monaco": ^3.1.0
  "@tailwindcss/typography": ^0.5.16
  "@tailwindcss/vite": ^4.0.9
  "@tanstack/react-router": ^1.111.11
  "@tanstack/router-devtools": ^1.111.11
  "@tanstack/router-plugin": ^1.111.12
  "@tsconfig/vite-react": ^3.4.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react": ^4.3.4
  clsx: ^2.1.1
  hono: ^4.7.2
  lefthook: ^1.11.2
  microcms-field-extension-api: ^1.0.0
  monaco-editor: ^0.52.2
  react: ^19.0.0
  react-dom: ^19.0.0
  react-icons: ^5.5.0
  react-remark: ^2.1.0
  react-use: ^17.6.0
  shiki: ^3.1.0
  sort-package-json: ^2.15.0
  tailwindcss: ^4.0.9
  turbo: ^2.4.4
  vite: ^6.2.0
  vite-tsconfig-paths: ^5.1.4
  wrangler: ^3.110.0
